#!/usr/bin/env python3
"""
Check that every documentation page is referenced in `nav_menu.md`.

Standalone CI check (standard library only): it scans the `docs` directory
for content pages (`.md` / `.html`) and verifies that each one appears as a
link target in `docs/nav_menu.md`. Navigation here is hand-maintained, so new
pages must be added to `nav_menu.md` by hand — this guards against forgetting.

Pages that should intentionally *not* appear in the navigation (for example
some section `index.md` files, or auto-generated files) are listed in the
`IGNORE` set below.

Exit code is 0 if every page is in the nav, 1 otherwise.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Repo paths: this file lives at <repo>/.github/scripts/check_nav.py
REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = REPO_ROOT / "docs"
NAV_FILE = DOCS_DIR / "nav_menu.md"

# File extensions treated as documentation content pages.
PAGE_SUFFIXES = {".md", ".html"}

# Directories (relative to DOCS_DIR) that never contain nav pages.
EXCLUDE_DIRS = {"scripts", "assets", "stylesheets", "__pycache__"}

# Pages allowed to be absent from nav_menu.md, as paths relative to DOCS_DIR
# using forward slashes. Add entries here for pages that should NOT appear in
# the navigation, e.g. some section index.md files or auto-generated files.
IGNORE = {
    "nav_menu.md",  # the navigation file itself
    "SUMMARY.md",  # auto-generated by the literate-nav hook
}


class MissingNavPagesError(Exception):
    """Raised when documentation pages are not referenced in nav_menu.md."""


def parse_link_targets(text: str) -> list[str]:
    """Return the raw link targets (the `...` in `[text](...)`) from markdown.

    Parsed line by line without regular expressions, expecting at most one link
    per line (as nav_menu.md is structured). Each line's single `](` opener is
    read up to its closing `)` on that same line. A `](` with no closing
    `)`, or a second link on the line, is malformed and raises `ValueError`.
    """
    targets = []
    opener = "]("
    for lineno, line in enumerate(text.splitlines(), start=1):
        start = line.find(opener)
        if start == -1:
            continue
        # open_paren indexes the "(", close_paren indexes just past the ")".
        open_paren = start + len("]")
        close = line.find(")", open_paren)
        if close == -1:
            raise ValueError(
                f"line {lineno}: unterminated '](' link (no closing ')'): {line!r}"
            )
        close_paren = close + 1
        if opener in line[close_paren:]:
            raise ValueError(
                f"line {lineno}: more than one link on a line: {line!r}"
            )
        delimited = line[open_paren:close_paren]
        assert delimited.startswith("(") and delimited.endswith(")"), delimited
        target = delimited[1:-1]
        if target:
            targets.append(target)
    return targets


def find_pages() -> set[str]:
    """Return all content pages under docs/, as paths relative to DOCS_DIR."""
    pages = set()
    for path in DOCS_DIR.rglob("*"):
        if not path.is_file() or path.suffix not in PAGE_SUFFIXES:
            continue
        rel = path.relative_to(DOCS_DIR)
        # Skip excluded dirs and hidden (dot-prefixed) paths.
        if any(part in EXCLUDE_DIRS for part in rel.parts):
            continue
        if any(part.startswith(".") for part in rel.parts):
            continue
        pages.add(rel.as_posix())
    return pages


def find_nav_targets() -> set[str]:
    """Return local link targets referenced in nav_menu.md."""
    targets = set()
    for raw in parse_link_targets(NAV_FILE.read_text(encoding="utf-8")):
        target = raw.strip()
        # Skip external links and in-page anchors.
        if target.startswith(("http://", "https://", "#", "mailto:")):
            continue
        # Drop any anchor / query suffix so paths compare cleanly.
        target = target.split("#", 1)[0].split("?", 1)[0]
        if target:
            targets.add(target)
    return targets


def main() -> int:
    if not NAV_FILE.exists():
        raise FileNotFoundError(f"nav file not found: {NAV_FILE}")

    pages = find_pages()
    nav_targets = find_nav_targets()

    missing = sorted(pages - nav_targets - IGNORE)

    if missing:
        rel_self = Path(__file__).resolve().relative_to(REPO_ROOT)
        listing = "\n".join(f"  - {page}" for page in missing)
        raise MissingNavPagesError(
            "the following pages are not referenced in nav_menu.md:\n"
            f"{listing}\n\n"
            f"Add each page to docs/nav_menu.md, or add it to IGNORE in "
            f"{rel_self} if it should not appear in the navigation."
        )

    print(f"OK: all {len(pages)} documentation pages are referenced in nav_menu.md.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
