site_name: CMIP7 Guidance and Documentation
theme:
  name: material
  logo: assets/CMIP_Icon_CMYK_negative.svg
  custom_dir: overrides
  features:
    - navigation.footer
    - search.suggest
    - header.autohide
  plugins:
    - search
    - optimize
    # - gen-files:
    #   scripts:
    #     - scripts/

  copyright: CCBY04 2025+ CMIP-IPO
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
extra_css: 
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - abbr
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
  - scripts/embed.js

nav:
  - CMIP7 Guidance: index.md
  - CMIP7: CMIP7/index.md
  - CMIP6: CMIP6/index.md
  - Docs Github: https://github.com/WCRP-CMIP/cmip7-guidance
